/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DocumentacaoRouteImport } from './routes/documentacao'
import { Route as FunilMarketingRouteImport } from './routes/funil-marketing'
import { Route as IncidentesRouteImport } from './routes/incidentes'
import { Route as LeadsRecentesRouteImport } from './routes/leads-recentes'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as AutomacoesIndexRouteImport } from './routes/automacoes.index'
import { Route as AutomacoesAutomationIdRouteImport } from './routes/automacoes.$automationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentacaoRoute = DocumentacaoRouteImport.update({
  id: '/documentacao',
  path: '/documentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const FunilMarketingRoute = FunilMarketingRouteImport.update({
  id: '/funil-marketing',
  path: '/funil-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentesRoute = IncidentesRouteImport.update({
  id: '/incidentes',
  path: '/incidentes',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRecentesRoute = LeadsRecentesRouteImport.update({
  id: '/leads-recentes',
  path: '/leads-recentes',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesIndexRoute = AutomacoesIndexRouteImport.update({
  id: '/automacoes/',
  path: '/automacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesAutomationIdRoute = AutomacoesAutomationIdRouteImport.update({
  id: '/automacoes/$automationId',
  path: '/automacoes/$automationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentacao': typeof DocumentacaoRoute
  '/funil-marketing': typeof FunilMarketingRoute
  '/incidentes': typeof IncidentesRoute
  '/leads-recentes': typeof LeadsRecentesRoute
  '/tarefas': typeof TarefasRoute
  '/automacoes/$automationId': typeof AutomacoesAutomationIdRoute
  '/automacoes/': typeof AutomacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentacao': typeof DocumentacaoRoute
  '/funil-marketing': typeof FunilMarketingRoute
  '/incidentes': typeof IncidentesRoute
  '/leads-recentes': typeof LeadsRecentesRoute
  '/tarefas': typeof TarefasRoute
  '/automacoes/$automationId': typeof AutomacoesAutomationIdRoute
  '/automacoes': typeof AutomacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentacao': typeof DocumentacaoRoute
  '/funil-marketing': typeof FunilMarketingRoute
  '/incidentes': typeof IncidentesRoute
  '/leads-recentes': typeof LeadsRecentesRoute
  '/tarefas': typeof TarefasRoute
  '/automacoes/$automationId': typeof AutomacoesAutomationIdRoute
  '/automacoes/': typeof AutomacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/documentacao'
    | '/funil-marketing'
    | '/incidentes'
    | '/leads-recentes'
    | '/tarefas'
    | '/automacoes/$automationId'
    | '/automacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/documentacao'
    | '/funil-marketing'
    | '/incidentes'
    | '/leads-recentes'
    | '/tarefas'
    | '/automacoes/$automationId'
    | '/automacoes'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/documentacao'
    | '/funil-marketing'
    | '/incidentes'
    | '/leads-recentes'
    | '/tarefas'
    | '/automacoes/$automationId'
    | '/automacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DocumentacaoRoute: typeof DocumentacaoRoute
  FunilMarketingRoute: typeof FunilMarketingRoute
  IncidentesRoute: typeof IncidentesRoute
  LeadsRecentesRoute: typeof LeadsRecentesRoute
  TarefasRoute: typeof TarefasRoute
  AutomacoesAutomationIdRoute: typeof AutomacoesAutomationIdRoute
  AutomacoesIndexRoute: typeof AutomacoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentacao': {
      id: '/documentacao'
      path: '/documentacao'
      fullPath: '/documentacao'
      preLoaderRoute: typeof DocumentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funil-marketing': {
      id: '/funil-marketing'
      path: '/funil-marketing'
      fullPath: '/funil-marketing'
      preLoaderRoute: typeof FunilMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidentes': {
      id: '/incidentes'
      path: '/incidentes'
      fullPath: '/incidentes'
      preLoaderRoute: typeof IncidentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads-recentes': {
      id: '/leads-recentes'
      path: '/leads-recentes'
      fullPath: '/leads-recentes'
      preLoaderRoute: typeof LeadsRecentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes/': {
      id: '/automacoes/'
      path: '/automacoes'
      fullPath: '/automacoes/'
      preLoaderRoute: typeof AutomacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes/$automationId': {
      id: '/automacoes/$automationId'
      path: '/automacoes/$automationId'
      fullPath: '/automacoes/$automationId'
      preLoaderRoute: typeof AutomacoesAutomationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DocumentacaoRoute: DocumentacaoRoute,
  FunilMarketingRoute: FunilMarketingRoute,
  IncidentesRoute: IncidentesRoute,
  LeadsRecentesRoute: LeadsRecentesRoute,
  TarefasRoute: TarefasRoute,
  AutomacoesAutomationIdRoute: AutomacoesAutomationIdRoute,
  AutomacoesIndexRoute: AutomacoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
