/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IncidentesRouteImport } from './routes/incidentes'
import { Route as SistemasRouteImport } from './routes/sistemas'
import { Route as AutomacoesIndexRouteImport } from './routes/automacoes.index'
import { Route as AutomacoesAutomationIdRouteImport } from './routes/automacoes.$automationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentesRoute = IncidentesRouteImport.update({
  id: '/incidentes',
  path: '/incidentes',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemasRoute = SistemasRouteImport.update({
  id: '/sistemas',
  path: '/sistemas',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesIndexRoute = AutomacoesIndexRouteImport.update({
  id: '/automacoes/',
  path: '/automacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesAutomationIdRoute = AutomacoesAutomationIdRouteImport.update({
  id: '/automacoes/$automationId',
  path: '/automacoes/$automationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/incidentes': typeof IncidentesRoute
  '/sistemas': typeof SistemasRoute
  '/automacoes/$automationId': typeof AutomacoesAutomationIdRoute
  '/automacoes/': typeof AutomacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/incidentes': typeof IncidentesRoute
  '/sistemas': typeof SistemasRoute
  '/automacoes/$automationId': typeof AutomacoesAutomationIdRoute
  '/automacoes': typeof AutomacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/incidentes': typeof IncidentesRoute
  '/sistemas': typeof SistemasRoute
  '/automacoes/$automationId': typeof AutomacoesAutomationIdRoute
  '/automacoes/': typeof AutomacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/incidentes'
    | '/sistemas'
    | '/automacoes/$automationId'
    | '/automacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/incidentes'
    | '/sistemas'
    | '/automacoes/$automationId'
    | '/automacoes'
  id:
    | '__root__'
    | '/'
    | '/incidentes'
    | '/sistemas'
    | '/automacoes/$automationId'
    | '/automacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IncidentesRoute: typeof IncidentesRoute
  SistemasRoute: typeof SistemasRoute
  AutomacoesAutomationIdRoute: typeof AutomacoesAutomationIdRoute
  AutomacoesIndexRoute: typeof AutomacoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidentes': {
      id: '/incidentes'
      path: '/incidentes'
      fullPath: '/incidentes'
      preLoaderRoute: typeof IncidentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas': {
      id: '/sistemas'
      path: '/sistemas'
      fullPath: '/sistemas'
      preLoaderRoute: typeof SistemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes/': {
      id: '/automacoes/'
      path: '/automacoes'
      fullPath: '/automacoes/'
      preLoaderRoute: typeof AutomacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes/$automationId': {
      id: '/automacoes/$automationId'
      path: '/automacoes/$automationId'
      fullPath: '/automacoes/$automationId'
      preLoaderRoute: typeof AutomacoesAutomationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IncidentesRoute: IncidentesRoute,
  SistemasRoute: SistemasRoute,
  AutomacoesAutomationIdRoute: AutomacoesAutomationIdRoute,
  AutomacoesIndexRoute: AutomacoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
